// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.livestormer.accounts.completeness;

import com.livestormer.accounts.completeness.AccountCompleteness;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AccountCompleteness_Roo_Configurable {
    
    declare @type: AccountCompleteness: @Configurable;
    
}
