// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.livestormer.accounts.completeness.tasks;

import com.livestormer.accounts.completeness.tasks.Task;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Task_Roo_Configurable {
    
    declare @type: Task: @Configurable;
    
}
