// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.livestormer.accounts.activities;

import com.livestormer.accounts.activities.Activity;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Activity_Roo_Configurable {
    
    declare @type: Activity: @Configurable;
    
}
